name: Build and Publish AFL Predictions

on:
  # Run daily at 1:00 UTC
  schedule:
    - cron: '0 1 * * *'
  # Also allow manual runs by clicking "Run workflow" in GitHub
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements to install"

      - name: Run scrape & predict script
        run: |
          python scrape_and_predict.py

      - name: Commit and push predictions_output.html to gh-pages
        run: |
          # Configure Git
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Create or switch to gh-pages branch
          git checkout -B gh-pages
          
          # Add the generated HTML
          git add predictions_output.html
          
          # Commit changes
          git commit -m "Update predictions [skip ci]" || echo "No changes to commit"
          
          # Push to gh-pages branch
          git push -f origin gh-pages
