name: Build and Publish AFL Predictions

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <--- Add this

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements to install"

      - name: Run scrape & predict script
        run: |
          python scrape_and_predict.py

      - name: Commit and push predictions_output.html to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B gh-pages
          git add predictions_output.html
          git commit -m "Update predictions [skip ci]" || echo "No changes to commit"
          git push -f origin gh-pages
